# Generated by Django 4.2.4 on 2023-09-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_apphistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="apphistory",
            name="instance_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="app",
            name="envs",
            field=models.JSONField(max_length=100),
        ),
        migrations.AlterField(
            model_name="apphistory",
            name="envs",
            field=models.JSONField(max_length=100),
        ),
        migrations.AlterField(
            model_name="apphistory",
            name="status",
            field=models.CharField(
                choices=[("RUNNING", "Running"), ("STOPPED", "Finnished")],
                default="RUNNING",
                max_length=100,
            ),
        ),
    ]
