# Generated by Django 4.2.4 on 2023-09-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_apphistory_instance_count_alter_app_envs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="command",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="app",
            name="envs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apphistory",
            name="command",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="apphistory",
            name="envs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
