# Generated by Django 4.2.4 on 2023-09-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_app_command_alter_app_envs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apphistory",
            name="instance_count",
        ),
        migrations.AlterField(
            model_name="app",
            name="command",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="app",
            name="image",
            field=models.CharField(max_length=150),
        ),
    ]
