# Generated by Django 4.2.4 on 2023-09-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_apphistory_instance_count_alter_app_command_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apphistory",
            name="status",
            field=models.CharField(
                choices=[("RUNNING", "Running"), ("FINNISHED", "Finnished")],
                default="RUNNING",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="AppInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="app.app",
                    ),
                ),
            ],
            options={
                "db_table": "app_instances",
            },
        ),
        migrations.AddField(
            model_name="apphistory",
            name="instance",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="history",
                to="app.appinstance",
            ),
            preserve_default=False,
        ),
    ]
